### ISSUE TITLE
Regarding the error "Fail to allocate bitmap" during the training process

### ISSUE THREAD

**Issue by hxdnshx** [PlayVoice/Grad-SVC#4]
I made modifications to the parameters in base.yaml:
```
full_epoch: Changed from 150 to 15000
batch_size: Changed from 8 to 24(18)
save_step: Changed from 10 to 100
```
My environment is:
```
Windows 10 22H2
CPU: 10850k
Memory: 64GiB
GPU: RTX 4090 64GiB
Pytorch 2.0.1+cu117
Python 3.8
```

During the training process, I encountered the following issues:

After running approximately +1030 Epochs, the following error message is frequently encountered:

```
Synthesis...
Fail to allocate bitmap
```

After running approximately +90 Epochs, the following error message can occasionally appear:
```
xception ignored in: <function Image.__del__ at 0x00000132B1459AF0>
Traceback (most recent call last):
  File "H:\Python389\lib\tkinter\__init__.py", line 4017, in __del__
    self.tk.call('image', 'delete', self.name)
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x00000132EA2C18B0>
Traceback (most recent call last):
  File "H:\Python389\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
RuntimeError: main thread is not in main loop
Exception ignored in: <function Variable.__del__ at 0x00000132EA2C18B0>
Traceback (most recent call last):
  File "H:\Python389\lib\tkinter\__init__.py", line 363, in __del__
    if self._tk.getboolean(self._tk.call("info", "exists", self._name)):
```

I'm not sure what caused these issues. Do you have any suggestions on how to pinpoint them? Thanks.

**Comment by MaxMax2016** [comment]
I have not meet the problems, I find some infos about the problems as :
https://stackoverflow.com/questions/67352611/fail-to-allocate-bitmap
https://github.com/PySimpleGUI/PySimpleGUI/issues/4009

**Comment by hxdnshx** [comment]
> I have not meet the problems, I find some infos about the problems as : https://stackoverflow.com/questions/67352611/fail-to-allocate-bitmap [PySimpleGUI/PySimpleGUI#4009](https://github.com/PySimpleGUI/PySimpleGUI/issues/4009)


Yes, I also noticed that document. I'm currently trying to set breakpoints in the code below based on the description in the document to reproduce the issue. I'll reply here if there's any further information.
https://github.com/PlayVoice/Grad-SVC/blob/eebee8536bd7febeb15ce700109d8016df06af39/grad_extend/utils.py#L75-L77

**Comment by hxdnshx** [comment]
After I commented out the code below, the issues related to the bitmap no longer occurred.

https://github.com/PlayVoice/Grad-SVC/blob/eebee8536bd7febeb15ce700109d8016df06af39/grad_extend/train.py#L100-L109

**Comment by MaxMax2016** [comment]
get it
