### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by pcunwa** [PlayVoice/Grad-SVC#5]
For testing, I set full_epochs to 15, fast_epochs to 10, and save_step to 5.
At the end of the 11th epoch, the following error message appears and the training is terminated.

Traceback (most recent call last):
  File "S:\VoiceChanger\Grad-SVC\gvc_trainer.py", line 30, in <module>
    train(hps, args.checkpoint_path)
  File "S:\VoiceChanger\Grad-SVC\grad_extend\train.py", line 127, in train
    prior_loss, diff_loss, mel_loss, spk_loss = model.compute_loss(
  File "S:\VoiceChanger\Grad-SVC\grad\model.py", line 132, in compute_loss
    mel = slice_segments(mel, ids, out_size)
  File "S:\VoiceChanger\Grad-SVC\grad\utils.py", line 82, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (200) must match the existing size (0) at non-singleton dimension 1.  Target sizes: [100, 200].  Tensor sizes: [100, 0]

**Comment by MaxMax2016** [comment]
Did you solve the problem？

**Comment by pcunwa** [comment]
Sorry for the delay in replying.
I updated with git pull and tested again, but the same problem still occurs at the same time...

**Comment by MaxMax2016** [comment]
mel = slice_segments(mel, ids, out_size)
Target sizes: [100, 200]. Tensor sizes: [100, 0] 
this means the mel is empty

**Comment by MaxMax2016** [comment]
you can check, if some file in './data_gvc/mel/' is to small.

**Comment by pcunwa** [comment]
The smallest file size is 37 KB.
Is this too small?

**Comment by MaxMax2016** [comment]
that's strange, Tensor sizes: [100, 0] mean mel is empty. and if data has error, every epoch will meat this error.
you can try to filter out error file in grad_extend/data.py
```
    def _filter(self):
        items_new = []
        # segment = 200
        items_min = 250  # 10ms * 250 = 2.5 S
        items_max = 500  # 10ms * 400 = 5.0 S
        for mel, vec, pit, spk in self.filelist:
            if not os.path.isfile(mel):
                continue
            if not os.path.isfile(vec):
                continue
            if not os.path.isfile(pit):
                continue
            if not os.path.isfile(spk):
                continue
            temp = np.load(pit)
            usel = int(temp.shape[0] - 1)  # useful length
            if (usel < items_min):
                continue
            if (usel >= items_max):
                usel = items_max
            items_new.append([mel, vec, pit, spk, usel])
        self.filelist = items_new
```

**Comment by pcunwa** [comment]
After manually deleting files that were not in the 2.5 to 5 second range, the training was successfully completed.

**Comment by pcunwa** [comment]
Sorry I closed the issue by mistake

**Comment by MaxMax2016** [comment]
the waves more than 5 second will be also used when train. if your waves are not enough, you should add them back.

**Comment by pcunwa** [comment]
I was able to confirm that the training completed successfully even after adding files longer than 5 seconds.
Thank you very much!
