### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by bukhalmae145** [PlayVoice/Grad-SVC#7]
python gvc_trainer.py

Numbers of GPU : True
Initializing logger...
Initializing data loaders...
----------131----------
----------10----------
Initializing model...
/Users/workstation/Music/Grad-SVC/Grad-SVC/lib/python3.8/site-packages/torch/nn/utils/weight_norm.py:30: UserWarning: torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.
  warnings.warn("torch.nn.utils.weight_norm is deprecated in favor of torch.nn.utils.parametrizations.weight_norm.")
Number of encoder parameters = 16.99m
Number of decoder parameters = 16.87m
Start from Grad_SVC pretrain model: grad_pretrain/gvc.pretrain.pth
Initializing optimizer...
Logging test batch...
Traceback (most recent call last):
  File "gvc_trainer.py", line 30, in <module>
    train(hps, args.checkpoint_path)
  File "/Users/workstation/Music/Grad-SVC/grad_extend/train.py", line 72, in train
    logger.add_image(f'image_{i}/ground_truth', plot_tensor(mel.squeeze()),
  File "/Users/workstation/Music/Grad-SVC/grad_extend/utils.py", line 59, in plot_tensor
    data = save_figure_to_numpy(fig)
  File "/Users/workstation/Music/Grad-SVC/grad_extend/utils.py", line 48, in save_figure_to_numpy
    data = data.reshape(fig.canvas.get_width_height()[::-1] + (3,))
ValueError: cannot reshape array of size 4320000 into shape (300,1200,3)

**Comment by MaxMax2016** [comment]
https://stackoverflow.com/questions/71602285/how-to-reshape-numpy-array-from-image-on-different-monitors-resolution

**Comment by MaxMax2016** [comment]
maybe you can try 
```
def canvas2rgb_array(canvas):
    """Adapted from: https://stackoverflow.com/a/21940031/959926"""
    canvas.draw()
    buf = np.frombuffer(canvas.tostring_rgb(), dtype=np.uint8)
    ncols, nrows = canvas.get_width_height()
    scale = round(math.sqrt(buf.size / 3 / nrows / ncols))
    return buf.reshape(scale * nrows, scale * ncols, 3)
```

**Comment by bukhalmae145** [comment]
> maybe you can try
> 
> ```
> def canvas2rgb_array(canvas):
>     """Adapted from: https://stackoverflow.com/a/21940031/959926"""
>     canvas.draw()
>     buf = np.frombuffer(canvas.tostring_rgb(), dtype=np.uint8)
>     ncols, nrows = canvas.get_width_height()
>     scale = round(math.sqrt(buf.size / 3 / nrows / ncols))
>     return buf.reshape(scale * nrows, scale * ncols, 3)
> ```

where should I adjust the code you gave?

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/Grad-SVC/blob/20230920-V2-96/grad_extend/utils.py#L46~L49
```
def save_figure_to_numpy(fig):
    data = np.fromstring(fig.canvas.tostring_rgb(), dtype=np.uint8, sep='')
    data = data.reshape(fig.canvas.get_width_height()[::-1] + (3,))
    return data
```
the code is not tested, because I don't have a development environment right now
```
def save_figure_to_numpy(fig):
    data = np.fromstring(fig.canvas.tostring_rgb(), dtype=np.uint8, sep='')
    ncols, nrows = fig.canvas.get_width_height()
    scale = round(math.sqrt(data.size / 3 / nrows / ncols))
    data = data.reshape(scale * nrows, scale * ncols, 3)
    return data
```

**Comment by bukhalmae145** [comment]
> https://github.com/PlayVoice/Grad-SVC/blob/20230920-V2-96/grad_extend/utils.py#L46~L49
> 
> ```
> def save_figure_to_numpy(fig):
>     data = np.fromstring(fig.canvas.tostring_rgb(), dtype=np.uint8, sep='')
>     data = data.reshape(fig.canvas.get_width_height()[::-1] + (3,))
>     return data
> ```
> 
> the code is not tested, because I don't have a development environment right now
> 
> ```
> def save_figure_to_numpy(fig):
>     data = np.fromstring(fig.canvas.tostring_rgb(), dtype=np.uint8, sep='')
>     ncols, nrows = fig.canvas.get_width_height()
>     scale = round(math.sqrt(data.size / 3 / nrows / ncols))
>     data = data.reshape(scale * nrows, scale * ncols, 3)
>     return data
> ```

error resolved! Thank you
