### ISSUE TITLE
Setting base.yaml

### ISSUE THREAD

**Issue by bukhalmae145** [PlayVoice/Grad-SVC#8]
What is the difference between full and fast epochs? And what are test size, test step, and save step?

**Comment by NLPV2011** [comment]
Full and fast epoch? I mean:
Full Epoch: for small dataset('cause if you use fast epoch for small dataset, the model is not have enough time to be train a good model, i think you need to enable it if your dataset less than 1hours of data)
Fast epoch: for large dataset(larger than 1hrs, if you enable full epoch to large data, the training step will very slowwww)

test_size, test step,  bruh, you no need to care too much =)))
save step? I mean this:
if you set save step to 500, the trainer will save model every 500 step, yeah ! =)))
